const test = require('node:test');
const assert = require('node:assert/strict');

const { parseHoldingsCsvToIngestionFile } = require('./.test-dist/holdings-csv-parser.js');

function parse(csv) {
  return parseHoldingsCsvToIngestionFile(csv, { fileId: 'test-file' });
}

test('parses a basic happy-path holdings CSV', () => {
  const csv = [
    'Account Number,Account Type,Symbol,CUSIP,Security Name,Shares,Market Value,Cost Basis,Acquisition Date',
    '123,Taxable Brokerage,VTI,,Vanguard Total Stock Market ETF,100,25000,20000,2022-05-15',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts.length, 1);
  assert.equal(result.accounts[0].holdings.length, 1);

  const holding = result.accounts[0].holdings[0];
  assert.equal(holding.ticker, 'VTI');
  assert.equal(holding.marketValue, 25000);
  assert.equal(holding.costBasis, 20000);
  assert.equal(holding.entryStatus, 'queued');
});

test('detects header row correctly when preamble rows exist', () => {
  const csv = [
    'Report generated by custodian',
    'As of 2026-04-07',
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '321,Taxable Brokerage,VOO,Vanguard 500 ETF,5',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts.length, 1);
  assert.equal(result.accounts[0].accountNumber, '321');
  assert.equal(result.accounts[0].holdings[0].ticker, 'VOO');
});

test('preserves sourceDataRowIndex relative to first data row after detected header', () => {
  const csv = [
    'intro line',
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '111,Taxable Brokerage,VTI,Vanguard Total Stock Market ETF,10',
    '111,Taxable Brokerage,VEA,Vanguard FTSE Developed Markets ETF,20',
  ].join('\n');

  const result = parse(csv);
  const holdings = result.accounts[0].holdings;
  assert.equal(holdings[0].sourceDataRowIndex, 0);
  assert.equal(holdings[1].sourceDataRowIndex, 1);
});

test('handles unquoted thousands separators without column misalignment', () => {
  const csv = [
    'Account Number,Account Type,Symbol,CUSIP,Security Name,Shares,Market Value,Cost Basis,Acquisition Date',
    '123,Taxable Brokerage,VTI,,Vanguard Total Stock Market ETF,100,$25,000,$20,000,2022-05-15',
  ].join('\n');

  const result = parse(csv);
  const holding = result.accounts[0].holdings[0];
  assert.equal(holding.marketValue, 25000);
  assert.equal(holding.costBasis, 20000);
  assert.equal(holding.acquisitionDate, '2022-05-15');
});

test('skips blank rows', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '',
    '123,Taxable Brokerage,VTI,Vanguard Total Stock Market ETF,100',
    '   ',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts[0].holdings.length, 1);
});

test('excludes subtotal/total rows from holdings and records issue', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '123,Taxable Brokerage,VTI,Vanguard Total Stock Market ETF,100',
    '123,Taxable Brokerage,Subtotal,,,',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts[0].holdings.length, 1);
  assert.ok(result.accounts[0].issues.some((x) => x.message.includes('Skipped likely subtotal/total row')));
});

test('emits UNMAPPED_ACCOUNT_TYPE when account type cannot be normalized', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '123,Crypto Vault,VTI,Vanguard Total Stock Market ETF,100',
  ].join('\n');

  const result = parse(csv);
  const issueCodes = result.accounts[0].issues.map((x) => x.code);
  assert.ok(issueCodes.includes('UNMAPPED_ACCOUNT_TYPE'));
  assert.equal(result.accounts[0].accountType, 'Unknown');
});


test('does not merge distinct unmapped account types into the same account bucket', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '123,Crypto Vault,VTI,Vanguard Total Stock Market ETF,100',
    '123,Trust Custody,VXUS,Vanguard Total International Stock ETF,200',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts.length, 2);
  const accountTypes = result.accounts.map((a) => a.accountType);
  assert.deepEqual(accountTypes, ['Unknown', 'Unknown']);
  result.accounts.forEach((account) => {
    const codes = account.issues.map((x) => x.code);
    assert.ok(codes.includes('UNMAPPED_ACCOUNT_TYPE'));
    assert.equal(account.holdings.length, 1);
  });
});


test('keeps holding/account IDs stable when rows are interleaved across accounts', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    'A1,Taxable Brokerage,VTI,Vanguard Total Stock Market ETF,10',
    'B2,Taxable Brokerage,VXUS,Vanguard Total International Stock ETF,20',
    'A1,Taxable Brokerage,BND,Vanguard Total Bond Market ETF,30',
    'B2,Taxable Brokerage,VEA,Vanguard FTSE Developed Markets ETF,40',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts.length, 2);

  const a1 = result.accounts.find((a) => a.accountNumber === 'A1');
  const b2 = result.accounts.find((a) => a.accountNumber === 'B2');
  assert.ok(a1);
  assert.ok(b2);

  assert.equal(a1.holdings.length, 2);
  assert.equal(b2.holdings.length, 2);

  a1.holdings.forEach((h) => assert.ok(h.holdingId.startsWith(`${a1.accountId}-h-`)));
  b2.holdings.forEach((h) => assert.ok(h.holdingId.startsWith(`${b2.accountId}-h-`)));

  assert.deepEqual(
    a1.holdings.map((h) => h.ticker),
    ['VTI', 'BND']
  );
  assert.deepEqual(
    b2.holdings.map((h) => h.ticker),
    ['VXUS', 'VEA']
  );
});

test('computes top-level reviewStatus from file + account + holding issues', () => {
  const csv = [
    'Account Number,Account Type,Symbol,Security Name,Shares',
    '123,Crypto Vault,VTI,Vanguard Total Stock Market ETF,100',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.issues.length, 0, 'this case is driven by account-level issues only');
  assert.equal(result.accounts[0].issues.length > 0, true);
  assert.equal(result.reviewStatus, 'in_review');
});

test('emits DUPLICATE_HOLDING for likely duplicate holdings in the same account', () => {
  const csv = [
    'Account Number,Account Type,Symbol,CUSIP,Security Name,Shares',
    '123,Taxable Brokerage,VTI,922908769,Vanguard Total Stock Market ETF,100',
    '123,Taxable Brokerage,VTI,922908769,Vanguard Total Stock Market ETF,100',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts[0].holdings.length, 2);
  const secondHoldingIssues = result.accounts[0].holdings[1].issues.map((x) => x.code);
  assert.ok(secondHoldingIssues.includes('DUPLICATE_HOLDING'));
});

test('flags invalid acquisitionDate format but keeps the holding', () => {
  const csv = [
    'Account Number,Account Type,Symbol,CUSIP,Security Name,Shares,Acquisition Date',
    '123,Taxable Brokerage,VTI,,Vanguard Total Stock Market ETF,100,04/07/2026',
  ].join('\n');

  const result = parse(csv);
  assert.equal(result.accounts[0].holdings.length, 1);
  const issueCodes = result.accounts[0].holdings[0].issues.map((x) => x.code);
  assert.ok(issueCodes.includes('INVALID_FORMAT'));
  assert.equal(result.reviewStatus, 'in_review');
});
